### ISSUE TITLE
Open project/folder in new window

### ISSUE THREAD

**Issue by btechgroup** [bobmagicii/vscode-dashboard#3]
currently it is not possible to open folder/project in new window. can you please add this option

**Comment by bobmagicii** [comment]
there was another user that asked this, and we had decided that this was better solved via the VS Code setting. is this solution acceptable or do you still have use cases?

![image](https://user-images.githubusercontent.com/881944/151266923-2ddcec7c-5e26-4175-9743-12e14fac99fe.png)

**Comment by btechgroup** [comment]
> there was another user that asked this, and we had decided that this was better solved via the VS Code setting. is this solution acceptable or do you still have use cases where it just needs to happen this one time?
> 
> my personal habit is to go file > new window (or ctrl+shift+n), which auto-opens the dashboard, and clicking a project consumes that fresh window.
> 
> we had to set this to "on" to get vscode to behave as you ask.
> 
> ![image](https://user-images.githubusercontent.com/881944/151266923-2ddcec7c-5e26-4175-9743-12e14fac99fe.png)

Thanks for your response. But I suggest if a project/folder have a context menu to open a particular project in new window.
<img width="401" alt="Screenshot 2022-01-27 at 06 43 47" src="https://user-images.githubusercontent.com/32300177/151305864-db7c60b0-a632-4723-a46b-9cd9bcf1c11e.png">

Thanks,

**Comment by bobmagicii** [comment]
fair enough

**Comment by bobmagicii** [comment]
bebeb26a68a8f9c9331ae0bdb4cc75d935fb9e1c adds menu options for opening in window or new

![image](https://user-images.githubusercontent.com/881944/152600364-9803468c-4c2c-4d25-b83e-205500115bb0.png)

4b24c709566a4ffbd807d5bd1d698b9c8d7b19a8 adds an option to make new window default

![image](https://user-images.githubusercontent.com/881944/152600440-6c46a8e9-f66b-4fef-9a08-a096f328e114.png)

update will be pushed into vscode marketplace this weekend.

**Comment by bobmagicii** [comment]
bebeb26a68a8f9c9331ae0bdb4cc75d935fb9e1c adds menu options for opening in window or new



4b24c709566a4ffbd807d5bd1d698b9c8d7b19a8 adds an option to make new window default



update will be pushed into vscode marketplace this weekend.

**Comment by btechgroup** [comment]
> [bebeb26](https://github.com/bobmagicii/vscode-dashboard/commit/bebeb26a68a8f9c9331ae0bdb4cc75d935fb9e1c) adds menu options for opening in window or new
> 
> ![image](https://user-images.githubusercontent.com/881944/152600907-f21ac576-43e0-494b-90d1-3bca06597623.png)
> 
> [4b24c70](https://github.com/bobmagicii/vscode-dashboard/commit/4b24c709566a4ffbd807d5bd1d698b9c8d7b19a8) adds an option to make new window default
> 
> ![image](https://user-images.githubusercontent.com/881944/152600938-005d509a-34e0-4ddb-9e75-9e5849432910.png)
> 
> update will be pushed into vscode marketplace this weekend.

Great Thanks a lot

**Comment by the-moog** [comment]
I'd like to re-open this as I would suggest that for remote projects a new window should be the default.  It makes no sense to lose the place you came from to get to the remote session address.  The remote session config may not know about other possible remote sessions. So you are stuck on an island.

Also the remote session configuration dialog is very, for want of a better phrase, "hair trigger..".

It has a button on which you click to open in a new window, but miss that with _either_ mouse button and it opens in the current window.  I.e. There is a button inside a much bigger button.  A more conventional UI click/right click or just two buttons may be easier.
