### ISSUE TITLE
Format project path on windows

### ISSUE THREAD

**Issue by biel-correa** [bobmagicii/vscode-dashboard#4]
The disk letter should be Uppercase, in the case of the image disk "C"

![image](https://user-images.githubusercontent.com/56176344/209454002-137e5e85-7cf3-42a7-b116-761b053d7185.png)

**Comment by bobmagicii** [comment]
microsoft clearly does not think so, it is coming out of their api. and it technically does not matter. but i agree. dcc94aeb95580e262c6340cb67d560ead41035fb

![image](https://user-images.githubusercontent.com/881944/213793587-c76ad244-2fed-4ad6-8034-b4c8a2d8e805.png)

![image](https://user-images.githubusercontent.com/881944/213793712-948faa3a-d629-4c52-90aa-0c5d36460c5f.png)
